server:
  port: 8080

spring:
  application:
    name: Security
  jwt:
    secret: vmfhaltmskdlstkfkdgodyroqkfwkdbalroqkfwkdbalaaaaaaaaaaaaaaaabbbbb

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/kpaas?useSSL=false&useUnicode=true&serverTimezone=Asia/Seoul&allowPublicKeyRetrieval=true
    username: manager_kpaas
    password: 7765

  jpa:
    hibernate:
      ddl-auto: validate
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl

logging:
  level:
    # Spring Security 전체에 대한 디버그 로그 활성화
    org.springframework.security: DEBUG
    # 웹 관련 로그도 함께 보면 좋음
    org.springframework.web: DEBUG